### ISSUE TITLE
Github actions

### ISSUE THREAD

**Issue by ShivanS93** [mrdbourke/nutrify#12]
I heard something about CI/CD.

Github action is good for this.

I have no idea how it works.

So I'm keen to tag along with this.

Edit: The idea is you commit your code and this will automatically update the production code. No downtime, all in one automated step.

**Comment by FlorianWoelki** [comment]
I think it would be better if @mrdbourke could set up a discussions section for ideas or improvements. But Github actions is a must though! :)

**Comment by ShivanS93** [comment]
Closing this and moving to discussions.
