### ISSUE TITLE
Capturing Image on mobile & page didn't refresh after upload

### ISSUE THREAD

**Issue by shabir15** [mrdbourke/nutrify#16]
Hello Daniel, Shabir here first of all amazing work and I have been following this project from the start . The problem I faced was when I opened the link on my android device , and clicked on browse files  I couldn't upload an image by capture , it took me to the screen to select photo from my mobile storage and also I noticed the page didn't refresh after I uploaded. I could see my image and other things as it is with the upload success message . Thanks again!

**Comment by mrdbourke** [comment]
Hey Shabir, thank you for the update!

Do you have a screenshot of what's happening? Hard to tell, I've only got an iPhone haha.

And when you uploaded, you mean the image didn't remove from the screen? I could fix that and make it disappear after upload.

Plenty more to come.

**Comment by shabir15** [comment]
Hehe! I figured u had iphone np. Yes image still stays and not able to use camera to click a photo directly takes me to the phone memory , also autofill doesn't work the second time I uploaded if it matters . Attached the screenshots

![852334c2-1c24-4a39-b8bc-198f26049410](https://user-images.githubusercontent.com/66748934/133271495-285ecf8d-a594-4204-aee4-fde02bcbba71.jpg)
![ee2df3b7-3cb0-4b60-81b3-f47807c2a80e](https://user-images.githubusercontent.com/66748934/133271497-0de34c65-8e67-4e9b-b767-67d640f31a71.jpg)
![b3ee7e47-e95a-446e-90fd-6fc35557d9ba](https://user-images.githubusercontent.com/66748934/133271499-e8d58cd6-4dd0-43e0-b44c-9b9f1a3147b4.jpg)

**Comment by shabir15** [comment]
Also in faq , on what happens to my image?  the text is same color as background so it's not visible , also I feel like increasing the text size a little more would be helpful. Thanks!

**Comment by shabir15** [comment]
all these happening in mobile  and also shouldn't it be why do we need images of food

**Comment by ShivanS93** [comment]
@shabir15 I'm able to take a photo whilst also uploading from my phones memory. I'm using Samsung A32.

FAQs look all visible to me, unless these issues have been fixed :)

**Comment by mrdbourke** [comment]
@ShivanS93 FAQs aren't visible when device is in darkmode due to colour of background text, I'll fix this today

I feel like the "not being able to use camera" isssue may be Android device specific (e.g. works on some but not others)

Adding functionality for the image to be removed when uploading is done now.

**Comment by mrdbourke** [comment]
added image/uploaded file removal, thank you for this, now onto making clearer text for FAQ
