### ISSUE TITLE
Change uploading size for an image

### ISSUE THREAD

**Issue by FlorianWoelki** [mrdbourke/nutrify#17]
Hey there!

Right now, it is possible to upload images that are up to 200mb big which I personally think is too much. In addition, I would be able (if streamlit does not prevent this) to upload 8k food images with a bot overnight to fill your Google bucket.

I suggest to kind of preprocessing the image in terms of size or changing the maximum file size. What do you think?

**Comment by mrdbourke** [comment]
Added to config a file size limit of 10MB, this is 20x smaller than default and should be enough for most images.

Also if someone ran a bot I think the Streamlit app would crash haha, it only has ~1GB of memory.

Can add checks later on to verify no bots.
