### ISSUE TITLE
A domain.

### ISSUE THREAD

**Issue by ShivanS93** [mrdbourke/nutrify#21]
Was looking up some domains.
https://www.nutrify.com/ - this is taken and it's a registered name. So does this mean the whole projects needs a new name? I hope not...

**Comment by mrdbourke** [comment]
I've got something for this :)

When it comes to custom domains, we should be right.

I'll keep seeing whether or not Streamlit hosting can use custom domains, otherwise it may be worth trying to host elsewhere.

**Comment by mrdbourke** [comment]
Closing this issue, domain is available at [https://nutrify.app](https://www.nutrify.app)
