### ISSUE TITLE
Add a button for asking "is this correct?"

### ISSUE THREAD

**Issue by mrdbourke** [mrdbourke/nutrify#37]
Every time there's a prediction, there should be an easy to use button asking "is this correct?".

The result of tapping this button will update a database prediction to say whether or not the prediction was right or wrong.

This will help evaluate the model(s) in the wild.

**Comment by mrdbourke** [comment]
I want to now add a button for “is this correct?” and then adding it to a database... I’ll build a small app to do that in the meantime.
* Supabase allows the functionality of adding functions to your database, so I’ll find it there: [https://youtu.be/MJZCCpCYEqk](https://youtu.be/MJZCCpCYEqk)
* Adding functionality into the database is helpful because it means you can change the front end of your app and the function in your database can still be called.
    * E.g. you could write the app in Python, Ruby, JavaScript etc and you just call the function from the database and pass it the appropriate variables.
        * See this post from Derek Sivers for more: [https://sive.rs/api01](https://sive.rs/api01)
            - Though there’s some debate about this here: https://softwareengineering.stackexchange.com/questions/158534/pros-and-cons-of-holding-all-the-business-logic-in-stored-procedures-in-web-appl
            - Is it necessary to have everything in a single place? If I just want to log predictions etc, can I do this all in one language?

Start as simple as possible:
* Button -> "Is this correct?" -> Yes/no -> Answer logged to database

**Comment by ShivanS93** [comment]
If it's on your business backend, then you can swap out the front-end without affecting how your code runs. Hope this makes sense with whatever decision you do.

I usually want the client-side to do as little as possible.

**Comment by mrdbourke** [comment]
Made some progress on this. Currently implemented a simple version in a toy app but I can merge it over to Nutrify.

Want to log:
* **UUID of the prediction (every upload/prediction gets a UUID)** - this will allow tracking across different instances/tables (this UUID gets attached the image, the prediction, the button press, etc)
* **Timestamp** - this is easy to do, Supabase can add it by default
* **Add "correct"/"not correct" bool** - have a column that's simple `true`/`false` in Postgres, can index on this
* **Add `fdc_id` prediction code** - this will be the food ID that the model predicted as being correct, with this we can index on the ID's with the *most* incorrect

Button functionality:
* **Make the button presses work only once** - this is easy, just make them disappear after a single click (some people may want to update their answers, but I feel this won't be 100% necessary to begin with, this functionality can be added when there is auth/accounts)
* **Add "thank you" message after the buttons are pressed** - be nice

**Comment by mrdbourke** [comment]
Done, added the functionality for a "is this correct?" button in #42 

The button will now log the results of whether predictions are correct or not (based on feedback from people) to a Supabase database.
