### ISSUE TITLE
Can't upload image

### ISSUE THREAD

**Issue by ShivanS93** [mrdbourke/nutrify#38]
`Uncaught SyntaxError: "0"-prefixed octal literals are deprecated; use the "0o" prefix instead`

This may be a known issue. This is console output when accessing the webpage.

I think this results in the upload not working (unless I'm mistaken).

The problem is in `constants.js` with `egg tart` having an id starting with `0`.

Hope this helps. Keep up the work.

**Comment by mrdbourke** [comment]
Yep you’re right, found this out last night haha. 

Made some updates & they didn’t work…

Will fix soon. 

Thank you for leaving an issue.

>

**Comment by ShivanS93** [comment]
Don't be afraid of reaching out to some contribution ;)

**Comment by mrdbourke** [comment]
Fixed this with latest commit, you were right was the 0's issue in the FDC ID's.

I'll likely be opening up public commits later on.

Who knows, perhaps we turn this into a startup at some point!
