### ISSUE TITLE
Creating a `config.py` or `config.yaml` for values of hyperparameters

### ISSUE THREAD

**Issue by ishandandekar** [mrdbourke/nutrify#49]
Noticed a **TODO** on line 174 of [nutrify/train.py](https://github.com/mrdbourke/nutrify/blob/main/train.py#L174), so thought of creating an issue ticket for it. Maybe something inspired from this [script](https://github.com/aladdinpersson/Machine-Learning-Collection/blob/master/ML/Kaggles/Dog%20vs%20Cat%20Competition/config.py). Maybe a `config.py` or `config.yaml` can be made. Hoping this helps!

**Comment by mrdbourke** [comment]
Now that you've given me the idea, I could definitely do it for a lot of the duplicate things I'm using across the `train.py` and `evaluate.py` (and soon) `fix_labels.py`.

Will look into this further when I've finished the overall data flywheel architecture.

**Comment by mrdbourke** [comment]
See here also for information on config setup ideas - https://12factor.net/config

**Comment by mrdbourke** [comment]
Done this, see here: https://github.com/mrdbourke/nutrify/tree/make_fix_labels_pipeline/foodvision/configs
