### ISSUE TITLE
Move all computer vision code into `foodvision`

### ISSUE THREAD

**Issue by mrdbourke** [mrdbourke/nutrify#57]
Should be a single directory for training FoodVision models.

Can break this down later into:
* `foodvision/classification` 
* `foodvision/detection`
* `foodvision/segmentation`

**Comment by mrdbourke** [comment]
Done, starting to build out `foodvision` library - https://github.com/mrdbourke/nutrify/tree/main/foodvision

**Comment by ishandandekar** [comment]
Maybe this can help - [https://github.com/abhishekkrthakur/mlframework](https://github.com/abhishekkrthakur/mlframework)
